# Generated by Django 3.1.2 on 2022-04-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clouds', '0002_auto_20220428_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='disc',
        ),
    ]
