# Generated by Django 3.1.2 on 2022-04-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clouds', '0003_auto_20220428_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('photo', models.ImageField(upload_to='Media/images')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
