# Generated by Django 3.1.2 on 2022-04-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clouds', '0005_auto_20220429_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageuploader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('photo', models.ImageField(upload_to='images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('desc', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
